---
- name: My first playbook
  hosts: webservers
  become: true  
  tasks:
    - name: Install httpd
      dnf:
          name: "{{ package_name }}"
          state: present
    - name: Start and enable httpd
      service:
          name: "{{ package_name }}"
          state: started
          enabled: true
