---
- name: Test vault variables
  hosts: webservers
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Print db password
      debug:
        msg: "The db password is {{ db_password }}"
