---
- name: Install httpd
  dnf:
    name: "{{ package_name }}"
    state: present
  notify: Restart httpd

- name: Copy httpd config
  copy:
    dest: /etc/httpd/conf/httpd.conf
    src: httpd.conf
  notify: Restart httpd

- name: Start and enable httpd
  service:
    name: "{{ package_name }}"
    state: started
    enabled: true
